apiVersion: v1
kind: ServiceAccount
metadata:
  name: opspilot-api
  labels:
    {{- include "opspilot.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opspilot-web
  labels:
    {{- include "opspilot.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opspilot-mysql
  labels:
    {{- include "opspilot.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
